# Generated by Django 5.1.14 on 2025-11-13 19:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Present",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        db_index=True,
                        default=django.utils.timezone.localdate,
                        help_text="The date of the attendance record.",
                    ),
                ),
                (
                    "present",
                    models.BooleanField(
                        default=False, help_text="Indicates if the user was present on this date."
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user this attendance record belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Time",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        db_index=True,
                        default=django.utils.timezone.localdate,
                        help_text="The date of the time entry.",
                    ),
                ),
                (
                    "time",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="The exact time of the event.",
                        null=True,
                    ),
                ),
                (
                    "out",
                    models.BooleanField(
                        default=False,
                        help_text="False for a time-in event, True for a time-out event.",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user this time entry belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecognitionAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When the recognition attempt was recorded.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Timestamp for the last update to this record."
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        help_text="Username inferred at recognition time (may be empty on failure).",
                        max_length=150,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("in", "Check-in"), ("out", "Check-out")],
                        help_text="Whether the attempt was for a check-in or check-out event.",
                        max_length=3,
                    ),
                ),
                (
                    "site",
                    models.CharField(
                        blank=True,
                        help_text="Physical location or site identifier for the attempt.",
                        max_length=255,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="System component that initiated the attempt (e.g. webcam, API).",
                        max_length=64,
                    ),
                ),
                (
                    "successful",
                    models.BooleanField(
                        default=False,
                        help_text="True when the attempt resulted in a successful recognition.",
                    ),
                ),
                (
                    "spoof_detected",
                    models.BooleanField(
                        default=False, help_text="True when anti-spoofing blocked the attempt."
                    ),
                ),
                (
                    "latency_ms",
                    models.FloatField(
                        blank=True,
                        help_text="End-to-end latency in milliseconds measured for the attempt.",
                        null=True,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Optional diagnostic information describing failures."
                    ),
                ),
                (
                    "present_record",
                    models.ForeignKey(
                        blank=True,
                        help_text="Linked daily presence record when one was created.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recognition_attempts",
                        to="users.present",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Resolved user for the attempt, if available.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recognition_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "time_record",
                    models.ForeignKey(
                        blank=True,
                        help_text="Linked time entry created for the attempt, if applicable.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recognition_attempts",
                        to="users.time",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="present",
            index=models.Index(fields=["user", "date"], name="users_present_user_date_idx"),
        ),
        migrations.AddIndex(
            model_name="present",
            index=models.Index(fields=["date", "user"], name="users_present_date_user_idx"),
        ),
        migrations.AddIndex(
            model_name="time",
            index=models.Index(fields=["user", "date"], name="users_time_user_date_idx"),
        ),
        migrations.AddIndex(
            model_name="time",
            index=models.Index(fields=["date", "user"], name="users_time_date_user_idx"),
        ),
        migrations.AddIndex(
            model_name="recognitionattempt",
            index=models.Index(fields=["site", "direction"], name="users_attempt_site_dir_idx"),
        ),
        migrations.AddIndex(
            model_name="recognitionattempt",
            index=models.Index(fields=["user", "direction"], name="users_attempt_user_dir_idx"),
        ),
        migrations.AddIndex(
            model_name="recognitionattempt",
            index=models.Index(fields=["created_at"], name="users_attempt_created_idx"),
        ),
    ]
