# Generated by Django 2.2.2 on 2019-06-28 06:25

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_auto_20190628_1114"),
    ]

    operations = [
        # Refactored to be database-agnostic (supports SQLite)
        migrations.RemoveField(
            model_name="attendance",
            name="time_in",
        ),
        migrations.AddField(
            model_name="attendance",
            name="time_in",
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="time_out",
        ),
        migrations.AddField(
            model_name="attendance",
            name="time_out",
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
