# Generated by Django 5.1.14 on 2025-11-08 08:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_auto_20240422_0000"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="present",
            name="date",
            field=models.DateField(
                default=django.utils.timezone.localdate,
                help_text="The date of the attendance record.",
            ),
        ),
        migrations.AlterField(
            model_name="present",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="present",
            name="present",
            field=models.BooleanField(
                default=False, help_text="Indicates if the user was present on this date."
            ),
        ),
        migrations.AlterField(
            model_name="present",
            name="user",
            field=models.ForeignKey(
                help_text="The user this attendance record belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="time",
            name="date",
            field=models.DateField(
                default=django.utils.timezone.localdate, help_text="The date of the time entry."
            ),
        ),
        migrations.AlterField(
            model_name="time",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="time",
            name="out",
            field=models.BooleanField(
                default=False, help_text="False for a time-in event, True for a time-out event."
            ),
        ),
        migrations.AlterField(
            model_name="time",
            name="time",
            field=models.DateTimeField(
                blank=True, help_text="The exact time of the event.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="time",
            name="user",
            field=models.ForeignKey(
                help_text="The user this time entry belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
