# Generated by Django 5.1.14 on 2025-11-11 05:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_add_attendance_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecognitionAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When the recognition attempt was recorded.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp for the last update to this record.",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        help_text="Username inferred at recognition time (may be empty on failure).",
                        max_length=150,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("in", "Check-in"), ("out", "Check-out")],
                        help_text="Whether the attempt was for a check-in or check-out event.",
                        max_length=3,
                    ),
                ),
                (
                    "site",
                    models.CharField(
                        blank=True,
                        help_text="Physical location or site identifier for the attempt.",
                        max_length=255,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="System component that initiated the attempt (e.g. webcam, API).",
                        max_length=64,
                    ),
                ),
                (
                    "successful",
                    models.BooleanField(
                        default=False,
                        help_text="True when the attempt resulted in a successful recognition.",
                    ),
                ),
                (
                    "spoof_detected",
                    models.BooleanField(
                        default=False,
                        help_text="True when anti-spoofing blocked the attempt.",
                    ),
                ),
                (
                    "latency_ms",
                    models.FloatField(
                        blank=True,
                        help_text="End-to-end latency in milliseconds measured for the attempt.",
                        null=True,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Optional diagnostic information describing failures.",
                    ),
                ),
                (
                    "present_record",
                    models.ForeignKey(
                        blank=True,
                        help_text="Linked daily presence record when one was created.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recognition_attempts",
                        to="users.present",
                    ),
                ),
                (
                    "time_record",
                    models.ForeignKey(
                        blank=True,
                        help_text="Linked time entry created for the attempt, if applicable.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recognition_attempts",
                        to="users.time",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Resolved user for the attempt, if available.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recognition_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["site", "direction"], name="users_attempt_site_dir_idx"),
                    models.Index(fields=["user", "direction"], name="users_attempt_user_dir_idx"),
                    models.Index(fields=["created_at"], name="users_attempt_created_idx"),
                ],
            },
        ),
    ]
