# Generated by Django 5.1.14 on 2025-11-29 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_recognitionattempt"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SetupWizardProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "current_step",
                    models.IntegerField(
                        choices=[
                            (1, "Organization Details"),
                            (2, "Camera & Liveness Test"),
                            (3, "Add First Employee"),
                            (4, "Train Recognition Model"),
                            (5, "Start Attendance Session"),
                        ],
                        default=1,
                        help_text="The current step in the setup wizard.",
                    ),
                ),
                (
                    "completed",
                    models.BooleanField(
                        default=False, help_text="Whether the wizard has been completed."
                    ),
                ),
                (
                    "org_name",
                    models.CharField(
                        blank=True, help_text="Organization name entered in step 1.", max_length=255
                    ),
                ),
                (
                    "org_timezone",
                    models.CharField(
                        blank=True,
                        help_text="Organization timezone entered in step 1.",
                        max_length=100,
                    ),
                ),
                (
                    "camera_tested",
                    models.BooleanField(
                        default=False, help_text="Whether the camera test was passed in step 2."
                    ),
                ),
                (
                    "liveness_tested",
                    models.BooleanField(
                        default=False, help_text="Whether the liveness test was passed in step 2."
                    ),
                ),
                (
                    "first_employee_username",
                    models.CharField(
                        blank=True,
                        help_text="Username of the first employee added in step 3.",
                        max_length=150,
                    ),
                ),
                (
                    "first_employee_photos_captured",
                    models.BooleanField(
                        default=False,
                        help_text="Whether photos were captured for the first employee in step 3.",
                    ),
                ),
                (
                    "model_trained",
                    models.BooleanField(
                        default=False, help_text="Whether the model was trained in step 4."
                    ),
                ),
                (
                    "training_task_id",
                    models.CharField(
                        blank=True, help_text="Celery task ID for the training job.", max_length=255
                    ),
                ),
                (
                    "first_session_started",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the first attendance session was started in step 5.",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the wizard progress was created."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When the wizard progress was last updated."
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="The admin user this wizard progress belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="setup_wizard_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Setup Wizard Progress",
                "verbose_name_plural": "Setup Wizard Progress",
            },
        ),
    ]
