# Generated by Django 5.1.14 on 2025-12-05 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_setup_wizard_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='direction',
            field=models.CharField(blank=True, choices=[('in', 'Check-in'), ('out', 'Check-out')], help_text='Whether this is a check-in or check-out event.', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='time',
            name='out',
            field=models.BooleanField(default=False, help_text='DEPRECATED: Use direction field instead. False for a time-in event, True for a time-out event.'),
        ),
    ]
