# Generated by Django 5.1.14 on 2025-12-05 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_populate_time_direction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="time",
            name="out",
        ),
    ]
