# Generated by Django 6.0.3 on 2026-04-06 07:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_remove_time_out_field"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="present",
            index=models.Index(fields=["date", "present"], name="users_present_date_present_idx"),
        ),
    ]
