# Generated by Django 6.0.3 on 2026-04-02 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_remove_time_out_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recognitionattempt",
            name="successful",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="True when the attempt resulted in a successful recognition.",
            ),
        ),
        migrations.AlterField(
            model_name="recognitionattempt",
            name="username",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Username inferred at recognition time (may be empty on failure).",
                max_length=150,
            ),
        ),
    ]
