# Generated by Django 6.0.4 on 2026-04-21 09:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_present_users_present_date_present_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="recognitionattempt",
            index=models.Index(
                fields=["user", "created_at"], name="users_attempt_user_created_idx"
            ),
        ),
    ]
