# Generated by Django 6.0.4 on 2026-04-25 07:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0019_recognitionattempt_users_attempt_user_created_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="recognitionattempt",
            index=models.Index(
                fields=["created_at", "successful"], name="users_attempt_created_succ_idx"
            ),
        ),
    ]
