# Generated by Django 5.1.14 on 2025-11-11 04:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RecognitionOutcome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("username", models.CharField(blank=True, max_length=150)),
                ("direction", models.CharField(blank=True, max_length=12)),
                ("source", models.CharField(blank=True, max_length=32)),
                ("accepted", models.BooleanField()),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("distance", models.FloatField(blank=True, null=True)),
                ("threshold", models.FloatField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["created_at", "direction"],
                        name="recognition_created_1e450f_idx",
                    ),
                    models.Index(
                        fields=["accepted", "created_at"],
                        name="recognition_accepte_1964df_idx",
                    ),
                ],
            },
        ),
    ]
