# Generated by Django 6.0.3 on 2026-04-02 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recognition", "0004_threshold_profile_group_support"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livenessresult",
            name="challenge_type",
            field=models.CharField(
                choices=[
                    ("motion", "Motion Detection"),
                    ("blink", "Blink Detection"),
                    ("head_turn", "Head Turn"),
                    ("anti_spoof", "Anti-Spoofing Model"),
                ],
                db_index=True,
                default="motion",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="recognitionoutcome",
            name="username",
            field=models.CharField(blank=True, db_index=True, max_length=150),
        ),
    ]
