# Generated by Django 6.0.5 on 2026-05-27 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recognition", "0004_threshold_profile_group_support"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="livenessresult",
            index=models.Index(fields=["challenge_type"], name="recognition_challen_a4cd53_idx"),
        ),
    ]
