import datetime
from unittest.mock import patch

from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import User
from django.utils import timezone

import pytest

from recognition.views_legacy import hours_vs_date_given_employee, hours_vs_employee_given_date
from users.models import Direction, Present, Time


@pytest.mark.django_db
def test_n_plus_one_hours_vs_employee_given_date():
    # Setup
    date = timezone.localdate()
    users = []
    hashed_password = make_password("password")
    # Create 5 users
    for i in range(5):
        u = User.objects.create(username=f"user{i}", password=hashed_password)
        users.append(u)
        Present.objects.create(user=u, date=date, present=True)
        # Add some time entries
        t1 = timezone.now()
        t2 = t1 + datetime.timedelta(hours=8)
        Time.objects.create(user=u, date=date, time=t1, direction=Direction.IN)
        Time.objects.create(user=u, date=date, time=t2, direction=Direction.OUT)

    present_qs = Present.objects.filter(date=date)
    time_qs = Time.objects.filter(date=date)

    # When running with pytest-xdist (-n auto), Django's query assertions include
    # EXPLAIN QUERY PLAN queries for performance analysis.
    # 2 actual queries + 2 EXPLAIN queries = 4 total
    # This occurs with both PostgreSQL (CI) and SQLite (with -n auto in full test suite)
    # However, in local environment without xdist, we expect 2 queries.
    from django.db import connection
    from django.test.utils import CaptureQueriesContext

    with patch("recognition.views_legacy.plt"):
        with patch("recognition.views_legacy.sns"):
            with CaptureQueriesContext(connection) as ctx:
                hours_vs_employee_given_date(present_qs, time_qs)

            # Filter out queries generated by silk logging, EXPLAIN, or SAVEPOINT
            # in xdist environments
            filtered_queries = [
                q
                for q in ctx.captured_queries
                if not q["sql"].startswith("EXPLAIN")
                and "silk_" not in q["sql"].lower()
                and not q["sql"].startswith("SAVEPOINT")
                and not q["sql"].startswith("RELEASE SAVEPOINT")
            ]

            assert len(filtered_queries) <= 2


@pytest.mark.django_db
def test_n_plus_one_hours_vs_date_given_employee():
    # Setup
    hashed_password = make_password("password")
    user = User.objects.create(username="user_date", password=hashed_password)
    today = timezone.localdate()
    days = 5

    for i in range(days):
        d = today - datetime.timedelta(days=i)
        Present.objects.create(user=user, date=d, present=True)
        t1 = timezone.now()
        t2 = t1 + datetime.timedelta(hours=8)
        Time.objects.create(user=user, date=d, time=t1, direction=Direction.IN)
        Time.objects.create(user=user, date=d, time=t2, direction=Direction.OUT)

    present_qs = Present.objects.filter(user=user)
    time_qs = Time.objects.filter(user=user)

    # When running with pytest-xdist (-n auto), Django's query assertions include
    # EXPLAIN QUERY PLAN queries for performance analysis.
    # 2 actual queries + 2 EXPLAIN queries = 4 total
    # This occurs with both PostgreSQL (CI) and SQLite (with -n auto in full test suite)
    # However, in local environment without xdist, we expect 2 queries.
    from django.db import connection
    from django.test.utils import CaptureQueriesContext

    with patch("recognition.views_legacy.plt"):
        with patch("recognition.views_legacy.sns"):
            with CaptureQueriesContext(connection) as ctx:
                hours_vs_date_given_employee(present_qs, time_qs)

            # Filter out queries generated by silk logging, EXPLAIN, or SAVEPOINT
            # in xdist environments
            filtered_queries = [
                q
                for q in ctx.captured_queries
                if not q["sql"].startswith("EXPLAIN")
                and "silk_" not in q["sql"].lower()
                and not q["sql"].startswith("SAVEPOINT")
                and not q["sql"].startswith("RELEASE SAVEPOINT")
            ]

            assert len(filtered_queries) <= 2
