name: Documentation Improvement
description: Suggest improvements or report issues with documentation
title: "[Docs]: "
labels: ["documentation", "docs"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping us improve our documentation! Please fill out the sections below.

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: Which documentation area does this relate to?
      options:
        - README
        - Quick Start Guide
        - User Guide
        - Developer Guide
        - Deployment Guide
        - API Reference
        - Architecture docs
        - Security docs
        - Other
    validations:
      required: true

  - type: textarea
    id: current-state
    attributes:
      label: Current State
      description: Describe the current state of the documentation or link to the relevant section.
      placeholder: |
        The current documentation says...
        Link: https://github.com/.../docs/...
    validations:
      required: true

  - type: textarea
    id: suggested-improvement
    attributes:
      label: Suggested Improvement
      description: What would you like to see changed or added?
      placeholder: |
        I suggest...
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this improvement?
      options:
        - Low - Nice to have
        - Medium - Would help users
        - High - Blocking or confusing users
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following before submitting.
      options:
        - label: I have searched existing issues to ensure this has not already been reported.
          required: true
        - label: I am willing to contribute a fix for this documentation issue.
          required: false
