name: Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature! Please fill out the sections below to help us understand your request.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe it.
      placeholder: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like.
      placeholder: A clear and concise description of what you want to happen...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.
      placeholder: List any workarounds or alternative approaches you've thought about...

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the system does this feature affect?
      options:
        - Face Recognition Pipeline
        - Web Interface / UI
        - Admin Dashboard
        - Employee Dashboard
        - API / Backend
        - Database / Storage
        - Authentication / Security
        - Deployment / Infrastructure
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Important
        - Critical for my use case
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: |
        Add any other context, mockups, or screenshots about the feature request here.
        Tip: You can attach images by clicking this area to highlight it and then dragging files in.
      placeholder: Any additional information that might help...

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following before submitting.
      options:
        - label: I have searched existing issues to ensure this feature has not already been requested.
          required: true
        - label: I have read the documentation to confirm this feature does not already exist.
          required: true
