apiVersion: v1
kind: ServiceAccount
metadata:
  name: attendance-sa
  namespace: attendance-system
  labels:
    app.kubernetes.io/name: attendance-system
    app.kubernetes.io/component: sa
automountServiceAccountToken: false
