---
name: pre-commit

"on":
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  # v4
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c  # v5
        with:
          python-version: "3.12"
          cache: pip
          cache-dependency-path: .pre-commit-config.yaml
      - name: Run pre-commit
        uses: pre-commit/action@46cb12b5093557e3f2824df9043216c52bb88a29  # v3.0.1
